#!/bin/bash

AWS_PROFILE=${AWS_PROFILE:="unset"}
AWS_PATH=~/.aws
AWS_SSO_JSON=$AWS_PATH/cli/cache/*.json
AWS_CREDENTIALS_FILE=$AWS_PATH/credentials

if [[ "$AWS_PROFILE" = "unset" ]] ; then
    read -p "Specify profile name: " AWS_PROFILE
fi

if [[ ! -d "$AWS_PATH/sso" ]] ; then
    echo -e "$0: error: AWS CLI not configured for sso yet
Run 'aws configure sso --profile $AWS_PROFILE' first.
See https://github.com/dotorg-lp/dotorg-lp for more info.
"
    exit
fi

if ! jq --version &> /dev/null ; then
    echo "Needs `jq`."
    exit
fi

echo "Generating credentials file for $AWS_PROFILE"

# Clear out any current credentials first
rm -f $AWS_CREDENTIALS_FILE
aws sso logout

aws sso login --profile $AWS_PROFILE
if aws sts get-caller-identity --profile $AWS_PROFILE > /dev/null ; then
    ACCESS_KEY=$(jq -j '.Credentials.AccessKeyId' $AWS_SSO_JSON)
    SECRET_KEY=$(jq -j '.Credentials.SecretAccessKey' $AWS_SSO_JSON)
    SESS_TOKEN=$(jq -j '.Credentials.SessionToken' $AWS_SSO_JSON)
else
    echo "$0: error: unable to login to aws sso with given account."
    exit
fi

echo -e "[$AWS_PROFILE]
aws_access_key_id=$ACCESS_KEY
aws_secret_access_key=$SECRET_KEY
aws_session_token=$SESS_TOKEN
" > $AWS_CREDENTIALS_FILE

echo "Credentials file generated."
